# seed/dummy_data.py

dummyProjects = [
    {
        "id": "1ef456",
        "name": "Website Redesign",
        "domain": "UI/UX",
        "budget": 5000,
        "deadline": "2025-10-15",
        "teamSize": 4,
        "description": "Revamp the company website with a modern interface and improved user experience.",
        "status": "Active",
        "priority": "High",
        "members": [
            {"id": "1f3e45", "name": "Priya Sharma", "role": "UI Designer"},
            {"id": "2g4h56", "name": "Arjun Patel", "role": "Frontend Developer"},
        ],
    },
    {
        "id": "2gh789",
        "name": "Mobile App Development",
        "domain": "FSD",
        "budget": 15000,
        "deadline": "2025-12-01",
        "teamSize": 6,
        "description": "Build a full-stack mobile application to enhance customer interaction.",
        "status": "Completed",
        "priority": "Medium",
        "members": [
            {"id": "4k6l78", "name": "Ravi Kumar", "role": "Project Manager"},
            {"id": "5m7n89", "name": "Neha Verma", "role": "Full Stack Developer"},
        ],
    },
    {
        "id": "3ij101",
        "name": "Cloud Migration",
        "domain": "Cloud",
        "budget": 8000,
        "deadline": "2025-11-20",
        "teamSize": 3,
        "description": "Shift existing services to a secure cloud infrastructure.",
        "status": "Active",
        "priority": "Low",
        "members": [{"id": "6p8q90", "name": "Sameer Khan", "role": "Cloud Engineer"}],
    },
    {
        "id": "4kl234",
        "name": "AI Chatbot Integration",
        "domain": "AI",
        "budget": 12000,
        "deadline": "2025-09-30",
        "teamSize": 5,
        "description": "Integrate AI-driven chatbot functionalities for customer support.",
        "status": "Active",
        "priority": "High",
        "members": [
            {"id": "7r1s23", "name": "Alok Das", "role": "AI Specialist"},
            {"id": "8t2u34", "name": "Pooja Singh", "role": "Backend Developer"},
        ],
    },
    {
        "id": "5mn678",
        "name": "Backend Optimization",
        "domain": "Backend",
        "budget": 9000,
        "deadline": "2025-10-25",
        "teamSize": 4,
        "description": "Optimize server-side operations and APIs for better performance.",
        "status": "Completed",
        "priority": "Medium",
        "members": [
            {"id": "9v3w45", "name": "Harshita Yadav", "role": "Backend Developer"},
            {"id": "1a2b34", "name": "Vikram Joshi", "role": "Database Administrator"},
        ],
    },
    {
        "id": "6op345",
        "name": "Security Enhancement",
        "domain": "Security",
        "budget": 7000,
        "deadline": "2025-11-10",
        "teamSize": 3,
        "description": "Implement advanced security protocols to safeguard data.",
        "status": "Active",
        "priority": "High",
        "members": [{"id": "2c3d45", "name": "Kavita Rani", "role": "Security Analyst"}],
    },
    {
        "id": "7qr901",
        "name": "Analytics Dashboard",
        "domain": "Data Science",
        "budget": 6000,
        "deadline": "2025-09-20",
        "teamSize": 3,
        "description": "Create interactive dashboards for business analytics and insights.",
        "status": "Completed",
        "priority": "Low",
        "members": [{"id": "3e4f56", "name": "Imran Ali", "role": "Data Analyst"}],
    },
]

dummyResources = [
    {
        "id": "1f3e45",
        "name": "Priya Sharma",
        "role": "UI Designer",
        "skills": ["UI Design", "Figma", "Adobe XD"],
        "experience": 4,
        "allocated": True,
        "project": {"id": "1ef456", "name": "Website Redesign"},
    },
    {
        "id": "2g4h56",
        "name": "Arjun Patel",
        "role": "Frontend Developer",
        "skills": ["HTML", "CSS", "JavaScript", "React"],
        "experience": 5,
        "allocated": True,
        "project": {"id": "1ef456", "name": "Website Redesign"},
    },
    {
        "id": "3i5j67",
        "name": "Meera Nair",
        "role": "UI/UX Designer",
        "skills": ["UI/UX Design", "Wireframing", "Prototyping", "Figma"],
        "experience": 3,
        "allocated": False,
        "project": None,
    },
    {
        "id": "4k6l78",
        "name": "Ravi Kumar",
        "role": "Project Manager",
        "skills": ["Project Planning", "Agile", "Scrum"],
        "experience": 7,
        "allocated": True,
        "project": {"id": "2gh789", "name": "Mobile App Development"},
    },
    {
        "id": "5m7n89",
        "name": "Neha Verma",
        "role": "Full Stack Developer",
        "skills": ["Node.js", "React", "MongoDB"],
        "experience": 4,
        "allocated": True,
        "project": {"id": "2gh789", "name": "Mobile App Development"},
    },
    {
        "id": "6p8q90",
        "name": "Sameer Khan",
        "role": "Cloud Engineer",
        "skills": ["AWS", "Docker", "Kubernetes"],
        "experience": 5,
        "allocated": True,
        "project": {"id": "3ij101", "name": "Cloud Migration"},
    },
    {
        "id": "7r1s23",
        "name": "Alok Das",
        "role": "AI Specialist",
        "skills": ["Machine Learning", "TensorFlow", "AI Ethics"],
        "experience": 6,
        "allocated": True,
        "project": {"id": "4kl234", "name": "AI Chatbot Integration"},
    },
    {
        "id": "8t2u34",
        "name": "Pooja Singh",
        "role": "Backend Developer",
        "skills": ["Node.js", "Express", "REST APIs"],
        "experience": 3,
        "allocated": True,
        "project": {"id": "4kl234", "name": "AI Chatbot Integration"},
    },
    {
        "id": "9v3w45",
        "name": "Harshita Yadav",
        "role": "Backend Developer",
        "skills": ["Python", "Django", "PostgreSQL"],
        "experience": 4,
        "allocated": True,
        "project": {"id": "5mn678", "name": "Backend Optimization"},
    },
    {
        "id": "1a2b34",
        "name": "Vikram Joshi",
        "role": "Database Administrator",
        "skills": ["SQL", "Performance Tuning", "Backup and Recovery"],
        "experience": 5,
        "allocated": True,
        "project": {"id": "5mn678", "name": "Backend Optimization"},
    },
    {
        "id": "2c3d45",
        "name": "Kavita Rani",
        "role": "Security Analyst",
        "skills": ["Network Security", "Penetration Testing", "Compliance"],
        "experience": 4,
        "allocated": True,
        "project": {"id": "6op345", "name": "Security Enhancement"},
    },
    {
        "id": "3e4f56",
        "name": "Imran Ali",
        "role": "Data Analyst",
        "skills": ["Excel", "Power BI", "SQL"],
        "experience": 3,
        "allocated": True,
        "project": {"id": "7qr901", "name": "Analytics Dashboard"},
    },
    {
        "id": "4g5h67",
        "name": "Ritika Sharma",
        "role": "UI/UX Designer",
        "skills": ["UI/UX Design", "Wireframing", "User Research"],
        "experience": 2,
        "allocated": False,
        "project": None,
    },
    {
        "id": "5h6i78",
        "name": "Manoj Verma",
        "role": "Cloud Engineer",
        "skills": ["AWS", "Terraform", "Monitoring"],
        "experience": 4,
        "allocated": False,
        "project": None,
    },
    {
        "id": "6i7j89",
        "name": "Shivam Tiwari",
        "role": "AI Researcher",
        "skills": ["Deep Learning", "Natural Language Processing"],
        "experience": 3,
        "allocated": False,
        "project": None,
    },
]
